### PR TITLE
[WIP] Add PCF on Azure for Enterprises

### PR DESCRIPTION
**Pull request by siennathesane**
**Work-In-Progress**

This isn't done yet, but I wanted to get the PR up early so it can go through the shared review process as I finish writing it.

This new document is not inherently designed to supplant the existing reference architecture, but provide a guide on how to deploy PCF in an Enterprise Architecture in Azure.

// cc @jastev @cwsteve2117 @ruckle @awmartin

### CODE REVIEW

**Comment by siennathesane** [comment]
//cc @telmosampaio @jorgecotillo

**Comment by siennathesane** [comment]
@jastev when you get a chance, can you please start looking through this and providing some initial feedback? Thanks!

**Comment by ljarzynski** [comment]
Hi @mxplusb ! Is this still a work in progress? Should we (the PCF Docs team) hold off on merging for now?

**Comment by ryanpei** [comment]
for anyone else who is referring to this PR - we're waiting for feedback from the MSFT team a.t.m.
thanks!
@pabloshuhmacher

**Pull request closed without merging**
