### PR TITLE
OpenStack reference architecture

### PR DESCRIPTION
**Pull request by skibum55**
OpenStack reference architecture added by c0 team @krishicks @pakiheart @jmcdice

### CODE REVIEW

**Comment by bentarnoff** [comment]
Thanks, @skibum55 !

**Comment by bentarnoff** [comment]
Hey @skibum55 which versions of PCF does this apply to? 1.8 through 1.11?

**Comment by skibum55** [comment]
I haven't seen 1.11 yet, but it's definitely good from 1.8 through 1.10

**Comment by bentarnoff** [comment]
Great, thanks.

**Pull request merged**
